### ISSUE TITLE
Reimplement Author display order

### ISSUE THREAD

**Issue by paluchas** [digital-york/oasis#150]
Follow up #29 and improve UI so that a user is only adding things once.

**Comment by paluchas** [comment]
@yf508 we ought to check [this Hyrax pull request](https://github.com/samvera/hyrax/pull/3079) before implementing our own solution.

**Comment by yf508** [comment]
NB: all existing records must be edited to make the orders correct.

**Comment by IAlferink** [comment]
@paluchas @yf508  I’ve tested the author display order. The order of the authors appearing in the output seems to work fine now. However, there are some issues that need to be resolved. In the summary details neither the publication nor the “How to cite this summary” are in proper APA format. The screenshot below shows what the output currently looks like.

Instead, the citation for the publication should look like this:

Doe, J., & Noname, J. (2013). Test title. Cognition. 50(2), 14-23

The citation when you click on the “How to cite this summary” button should look like this:

Doe, J. & Noname, J., (2018). Current thinking on test title. OASIS Summary of Doe, J. & Noname, J. (2013) in Cognition. https://oasis-database.org

Can these things be resolved?

In addition, I was wondering if there could be and ampersand instead of a comma between the two names in the “Writer of summary” section. 

<img width="1178" alt="screen shot 2018-07-10 at 15 41 01" src="https://user-images.githubusercontent.com/40735172/42518752-7d4c1436-845a-11e8-9eb9-78e1792f78ba.png">

**Comment by IAlferink** [comment]
One more thing. Could the "writer of summary" field be Surname, Initial?

**Comment by IAlferink** [comment]
@paluchas @yf508 Apologies, I commented on this, but didn't realise I had to re-open the issue.

**Comment by yf508** [comment]
Just discovered a small display bug, waits to be fixed until #166 being merged as there are some conflicts identified.
