### ISSUE TITLE
Deposit agreement (link on Upload form) needs to be updated to reflect correct visibility option that user is given when uploading a summary

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#153]
Once correct workflow / process for uploading a summary and making it public has been implemented (#151 ), the deposit agreement text needs to be updated.

**Comment by paluchas** [comment]
Question: Do we want to revert to default Hyrax UI where a user can agree to terms and condition alongside with changing the summary visibility. 

Following is the image with Hyrax default behaviour
![screen shot 2018-05-30 at 10 14 14](https://user-images.githubusercontent.com/1863245/40711120-5020186e-63f2-11e8-9ec8-ff0ba12b6366.png)

Here is how we implemented this so far
![screen shot 2018-05-30 at 10 15 56](https://user-images.githubusercontent.com/1863245/40711250-9c3e3582-63f2-11e8-89b0-190504a8c6f7.png)

**Comment by yf508** [comment]
@RKasprowicz @IAlferink Please could you provide me with the updated texts?

**Comment by IAlferink** [comment]
@yf508 @paluchas I'm a little confused. Are the private / public options staying? I thought all the summaries would be public?

**Comment by yf508** [comment]
I think you are right, we only need 'public'.

**Comment by IAlferink** [comment]
@em502 Just want to check that you agree with this. Currently, there are private/public options when people submit a summary. It seems that with the new workflow we don't both as all summaries will be 'pending' review and then 'public'.

**Comment by em502** [comment]
Yes Inge,
All uploaders outside the OASIS team must choose  "pending review",  so
it's safest to remove any option completely for them
(Or, if it is not possible to only give them the "pending review" option,
then tell them clearly they have to click this one as all summaries are
checked over before going public
E.g. "You must click "Pending Review" as all summaries must be sent for a
check by OASIS team before they are made public")

Is it possible to change the wording to "Pending Check" please? ("Review"
sounds a bit more formal than what we have the capacity for). But if this
is difficult in any way just leave as "Pending Review"!!

NB Of course, the OASIS team WILL want both options, "pending review" and
"public", so, it might be set like this because it is very difficult to
have two systems in place,  I.e. one for everyone else and one for OASIS
team.
If it's too difficult to have two systems,  then as I said above, we just
need to tell the general uploader to choose "Pending Check" (or Review...)

Thanks for checking Inge.

Inge, please could you incorporate my response here into GitHub, (and also
the last email I sent about something else), so all our discussion is in
one place? (I'm not accessing GitHub from my phone!)

All best
Emma

**Comment by IAlferink** [comment]
So, we want to 
1) Remove the private option alltogether

2) Then either 
option a) Have depositors check Public - pending check, which changes to public when the summary is approved

**or** if that's not possible

option b) Have depositors just check public with noting in the description that it will be checked and approved first
<img width="364" alt="screen shot 2018-08-03 at 09 23 47" src="https://user-images.githubusercontent.com/40735172/43632764-f85aa316-96fe-11e8-9dab-8caf2f757fd1.png">

**Comment by IAlferink** [comment]
@RKasprowicz Side note: I think we should change the _save_ button at the bottom to _submit_ as, for me, _save_ suggests you can go back and edit, but _submit_ doesn't. What do you think?

**Comment by RKasprowicz** [comment]
@IAlferink I agree Inge, if it is possible to change the button text, then yes _Submit_ would work better.

**Comment by IAlferink** [comment]
@RKasprowicz Ok, thanks. I'll create a new issue

**Comment by IAlferink** [comment]
@yf508 Here is the link to the updated deposit agreement: https://docs.google.com/document/d/1DgImqjAnD5MBDiV02YXkszjaG9J3mHYEuVtFHNMPMqU/edit?usp=sharing

**Comment by em502** [comment]
thanks Inge . yes a) "Public - pending check" on the button or b) "Public"
with a note below are both fine.  And if a) is at all difficult, b) really
is just FINE!

*Also,* do we have to keep the words from
"Please note, making something visible to the world...[to]... about
publisher copyright policies" ?

*I think that this can all be cut entirely.*  I think it could worry some
people - as they might also be in the process of publishing their article
and might think that this affects that process somehow - and it certainly
does not- so we don't want to worry them. There isn't an issue with
patents.

This will leave just the following in the description below:
"Make available to all, pending check by OASIS team"

Emma

**Comment by IAlferink** [comment]
@em502 I think you're right and it could worry people. There is a disclaimer in the deposit agreement about copyrighted work, so there is no need for this to be on the upload form.

**Comment by yf508** [comment]
@IAlferink The deposit agreement can be updated here via the UI: https://dev.oasis-database.org/pages/edit?locale=en#agreement

**Comment by IAlferink** [comment]
@yf508 Great, I'll update it then. Thanks
