### ISSUE TITLE
Author display order

### ISSUE THREAD

**Issue by brazen-guff** [digital-york/oasis#29]
Investigate why author display order is changed on results page.

**Comment by paluchas** [comment]
This issue is related how metadata are stored in Fedora and Solr. By default, Hyrax is not offering the ability to preserve an order of metadata as entered. What we see on the UI is driven by content as saved in Solr search index (this might be different than as it is stored in Fedora). 

There is an ongoing discussion in the community how this should be fixed at [this Samvera tech list thread.](https://groups.google.com/forum/#!searchin/samvera-tech/data$20ordering%7Csort:date/samvera-tech/g1oa5B2B0Wk/51pa6lxQAQAJ)

**Comment by paluchas** [comment]
The possible options here are:
1. Wait for the community solution
2. Use single author field with multiple authors entered as one string
3. Implement our ordering hack

My prefered option is to wait for the community solution. The drawback is we don't know the timescale for this and most likely will not be implemented before official OASIS launch.

Option 2  preserves order but will not allow for a single author based facet search. 
Option 3  will not be developed before service official launch. 

All options will require some work to realign order of authors in existing data once option 1 is available.

**Comment by paluchas** [comment]
See proposed temporary solution - comments on #32

**Comment by RKasprowicz** [comment]
@paluchas I changed label to UAT - ready as the temporary solution is working.

**Comment by paluchas** [comment]
@RKasprowicz @SophieThompson We are still considering wheater this could be implemented differently. 

At present implementation (once those bugs are solved #98, #97, #96) the order of authors should be presented correctly on brief search results and detailed summary pages. However, with this approach, we won't be able to reconstruct the original order of all authors once a community solution will be available. This means that in future some manual updated of all records will be required to reorder all individual name entries.
