### ISSUE TITLE
Upload form: Information for a summary is not retained when "edit" is selected on an exisiting entry

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#53]
Selecting "edit" for an existing summary entry, causes some information to be forgotten, and other information to be presented incorrectly: 

For example DOI has been replaced with data for "pages: from" in the below:
![image](https://user-images.githubusercontent.com/36402489/36556804-5046c012-17fe-11e8-8e83-272dc06bc8ce.png)

And information is no longer displaying for the fields below: 
![image](https://user-images.githubusercontent.com/36402489/36556840-7460a0d0-17fe-11e8-86bb-e8b3b813dd86.png)

**Comment by paluchas** [comment]
We still need to replicate the above bug on the demo site. 

In addition, on my dev environment (tested on this [commit](https://github.com/digital-york/oasis/commit/8f4e8ee909049109d950c483f22e15480dcd1cd9) I had noticed that the following fields will not populate correct values as stored in Fedora and Solr:
* participants_domain_of_use (Context of Language Use)
* of_likely_interest_to (Of likely interest to ...)
* comments (Comments on the submission process)
* summary_notes (Notes)

@yf508 note, that when I have changed the two fields partial to use forms with "select" instead of the "check_boxes" the correct values were populated in edit mode.

**Comment by paluchas** [comment]
@RKasprowicz I was not able to replicate your specific bug. However, I have added some changes to our demo site to resolve issues as reported by me. The demo site has some numerous changes. Can you test this specific bug once again, please? Please report any further discoveries here.

If it works can you indicate this at #56 with "UAT - ready" label.

**Comment by yf508** [comment]
This info might be related: 

Unpermitted parameters: :licence_agreement, :representative_id, :thumbnail_id, :admin_set_id, :member_of_collection_ids, :visibility, :visibility_during_embargo, :embargo_release_date, :visibility_after_embargo, :visibility_during_lease, :lease_expiration_date, :visibility_after_lease

**Comment by RKasprowicz** [comment]
@paluchas I tried to edit the information for one of the summaries I have previously uploaded. When I clicked edit, the information did seem to be displaying correctly. However, when I  clicked save again I got the following error message:
![image](https://user-images.githubusercontent.com/36402489/37090838-d3d57ef6-21fd-11e8-886b-7b4bce407f27.png)
